/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 31
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_identifier = 2,
  sym_string = 3,
  anon_sym_workspace = 4,
  anon_sym_extends = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_model = 8,
  anon_sym_views = 9,
  anon_sym_name = 10,
  anon_sym_description = 11,
  sym_source_file = 12,
  sym__value = 13,
  sym__definition = 14,
  sym_workspace = 15,
  sym_workspace_block = 16,
  sym_model = 17,
  sym_model_block = 18,
  sym_views = 19,
  sym_views_block = 20,
  sym_name_statement = 21,
  sym_description_statement = 22,
  aux_sym_source_file_repeat1 = 23,
  aux_sym_workspace_block_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_identifier] = "identifier",
  [sym_string] = "string",
  [anon_sym_workspace] = "workspace",
  [anon_sym_extends] = "extends",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_model] = "model",
  [anon_sym_views] = "views",
  [anon_sym_name] = "name",
  [anon_sym_description] = "description",
  [sym_source_file] = "source_file",
  [sym__value] = "_value",
  [sym__definition] = "_definition",
  [sym_workspace] = "workspace",
  [sym_workspace_block] = "workspace_block",
  [sym_model] = "model",
  [sym_model_block] = "model_block",
  [sym_views] = "views",
  [sym_views_block] = "views_block",
  [sym_name_statement] = "name_statement",
  [sym_description_statement] = "description_statement",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_workspace_block_repeat1] = "workspace_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_identifier] = sym_identifier,
  [sym_string] = sym_string,
  [anon_sym_workspace] = anon_sym_workspace,
  [anon_sym_extends] = anon_sym_extends,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_model] = anon_sym_model,
  [anon_sym_views] = anon_sym_views,
  [anon_sym_name] = anon_sym_name,
  [anon_sym_description] = anon_sym_description,
  [sym_source_file] = sym_source_file,
  [sym__value] = sym__value,
  [sym__definition] = sym__definition,
  [sym_workspace] = sym_workspace,
  [sym_workspace_block] = sym_workspace_block,
  [sym_model] = sym_model,
  [sym_model_block] = sym_model_block,
  [sym_views] = sym_views,
  [sym_views_block] = sym_views_block,
  [sym_name_statement] = sym_name_statement,
  [sym_description_statement] = sym_description_statement,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_workspace_block_repeat1] = aux_sym_workspace_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_workspace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extends] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_model] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_views] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_name] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_description] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_workspace] = {
    .visible = true,
    .named = true,
  },
  [sym_workspace_block] = {
    .visible = true,
    .named = true,
  },
  [sym_model] = {
    .visible = true,
    .named = true,
  },
  [sym_model_block] = {
    .visible = true,
    .named = true,
  },
  [sym_views] = {
    .visible = true,
    .named = true,
  },
  [sym_views_block] = {
    .visible = true,
    .named = true,
  },
  [sym_name_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_description_statement] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_workspace_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_base = 1,
  field_body = 2,
  field_description = 3,
  field_name = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_base] = "base",
  [field_body] = "body",
  [field_description] = "description",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 1},
  [1] =
    {field_body, 2},
    {field_name, 1},
  [3] =
    {field_base, 2},
    {field_body, 3},
  [5] =
    {field_value, 1},
  [6] =
    {field_body, 3},
    {field_description, 2},
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(41);
      ADVANCE_MAP(
        '"', 3,
        '#', 42,
        '/', 4,
        'd', 11,
        'e', 39,
        'm', 25,
        'n', 5,
        'v', 17,
        'w', 26,
        '{', 54,
        '}', 55,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'e') ADVANCE(48);
      if (lookahead == '{') ADVANCE(54);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '{') ADVANCE(54);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(50);
      if (lookahead == '\\') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(42);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(31);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(35);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(12);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 20:
      if (lookahead == 'k') ADVANCE(34);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(56);
      END_STATE();
    case 22:
      if (lookahead == 'm') ADVANCE(15);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(59);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 28:
      if (lookahead == 'p') ADVANCE(6);
      END_STATE();
    case 29:
      if (lookahead == 'p') ADVANCE(37);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 31:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 32:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(57);
      END_STATE();
    case 34:
      if (lookahead == 's') ADVANCE(28);
      END_STATE();
    case 35:
      if (lookahead == 's') ADVANCE(52);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 38:
      if (lookahead == 'w') ADVANCE(33);
      END_STATE();
    case 39:
      if (lookahead == 'x') ADVANCE(36);
      END_STATE();
    case 40:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(46);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(45);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(43);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(53);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(44);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'x') ADVANCE(47);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_workspace);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_extends);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_extends);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_model);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_views);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_name);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_description);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(1),
    [anon_sym_workspace] = ACTIONS(1),
    [anon_sym_extends] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_model] = ACTIONS(1),
    [anon_sym_views] = ACTIONS(1),
    [anon_sym_name] = ACTIONS(1),
    [anon_sym_description] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(28),
    [sym__definition] = STATE(5),
    [sym_workspace] = STATE(5),
    [sym_model] = STATE(5),
    [sym_views] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_workspace] = ACTIONS(7),
    [anon_sym_model] = ACTIONS(9),
    [anon_sym_views] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_model,
    ACTIONS(11), 1,
      anon_sym_views,
    ACTIONS(13), 1,
      anon_sym_RBRACE,
    ACTIONS(15), 1,
      anon_sym_name,
    ACTIONS(17), 1,
      anon_sym_description,
    STATE(3), 5,
      sym_model,
      sym_views,
      sym_name_statement,
      sym_description_statement,
      aux_sym_workspace_block_repeat1,
  [26] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_model,
    ACTIONS(11), 1,
      anon_sym_views,
    ACTIONS(15), 1,
      anon_sym_name,
    ACTIONS(17), 1,
      anon_sym_description,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    STATE(4), 5,
      sym_model,
      sym_views,
      sym_name_statement,
      sym_description_statement,
      aux_sym_workspace_block_repeat1,
  [52] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_RBRACE,
    ACTIONS(23), 1,
      anon_sym_model,
    ACTIONS(26), 1,
      anon_sym_views,
    ACTIONS(29), 1,
      anon_sym_name,
    ACTIONS(32), 1,
      anon_sym_description,
    STATE(4), 5,
      sym_model,
      sym_views,
      sym_name_statement,
      sym_description_statement,
      aux_sym_workspace_block_repeat1,
  [78] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_workspace,
    ACTIONS(9), 1,
      anon_sym_model,
    ACTIONS(11), 1,
      anon_sym_views,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    STATE(6), 5,
      sym__definition,
      sym_workspace,
      sym_model,
      sym_views,
      aux_sym_source_file_repeat1,
  [101] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(39), 1,
      anon_sym_workspace,
    ACTIONS(42), 1,
      anon_sym_model,
    ACTIONS(45), 1,
      anon_sym_views,
    STATE(6), 5,
      sym__definition,
      sym_workspace,
      sym_model,
      sym_views,
      aux_sym_source_file_repeat1,
  [124] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 7,
      ts_builtin_sym_end,
      anon_sym_workspace,
      anon_sym_RBRACE,
      anon_sym_model,
      anon_sym_views,
      anon_sym_name,
      anon_sym_description,
  [137] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 7,
      ts_builtin_sym_end,
      anon_sym_workspace,
      anon_sym_RBRACE,
      anon_sym_model,
      anon_sym_views,
      anon_sym_name,
      anon_sym_description,
  [150] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 7,
      ts_builtin_sym_end,
      anon_sym_workspace,
      anon_sym_RBRACE,
      anon_sym_model,
      anon_sym_views,
      anon_sym_name,
      anon_sym_description,
  [163] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 7,
      ts_builtin_sym_end,
      anon_sym_workspace,
      anon_sym_RBRACE,
      anon_sym_model,
      anon_sym_views,
      anon_sym_name,
      anon_sym_description,
  [176] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(58), 1,
      sym_string,
    ACTIONS(60), 1,
      anon_sym_extends,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    STATE(12), 1,
      sym__value,
    STATE(15), 1,
      sym_workspace_block,
  [198] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    STATE(18), 1,
      sym_workspace_block,
    STATE(26), 1,
      sym__value,
    ACTIONS(64), 2,
      sym_identifier,
      sym_string,
  [215] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 5,
      anon_sym_RBRACE,
      anon_sym_model,
      anon_sym_views,
      anon_sym_name,
      anon_sym_description,
  [226] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 5,
      anon_sym_RBRACE,
      anon_sym_model,
      anon_sym_views,
      anon_sym_name,
      anon_sym_description,
  [237] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 4,
      ts_builtin_sym_end,
      anon_sym_workspace,
      anon_sym_model,
      anon_sym_views,
  [247] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 4,
      ts_builtin_sym_end,
      anon_sym_workspace,
      anon_sym_model,
      anon_sym_views,
  [257] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 4,
      ts_builtin_sym_end,
      anon_sym_workspace,
      anon_sym_model,
      anon_sym_views,
  [267] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 4,
      ts_builtin_sym_end,
      anon_sym_workspace,
      anon_sym_model,
      anon_sym_views,
  [277] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 4,
      ts_builtin_sym_end,
      anon_sym_workspace,
      anon_sym_model,
      anon_sym_views,
  [287] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 4,
      ts_builtin_sym_end,
      anon_sym_workspace,
      anon_sym_model,
      anon_sym_views,
  [297] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(27), 1,
      sym__value,
    ACTIONS(82), 2,
      sym_identifier,
      sym_string,
  [308] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(14), 1,
      sym__value,
    ACTIONS(84), 2,
      sym_identifier,
      sym_string,
  [319] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(13), 1,
      sym__value,
    ACTIONS(86), 2,
      sym_identifier,
      sym_string,
  [330] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_LBRACE,
    STATE(7), 1,
      sym_model_block,
  [340] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      sym_views_block,
  [350] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    STATE(20), 1,
      sym_workspace_block,
  [360] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    STATE(16), 1,
      sym_workspace_block,
  [370] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
  [377] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_RBRACE,
  [384] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 52,
  [SMALL_STATE(5)] = 78,
  [SMALL_STATE(6)] = 101,
  [SMALL_STATE(7)] = 124,
  [SMALL_STATE(8)] = 137,
  [SMALL_STATE(9)] = 150,
  [SMALL_STATE(10)] = 163,
  [SMALL_STATE(11)] = 176,
  [SMALL_STATE(12)] = 198,
  [SMALL_STATE(13)] = 215,
  [SMALL_STATE(14)] = 226,
  [SMALL_STATE(15)] = 237,
  [SMALL_STATE(16)] = 247,
  [SMALL_STATE(17)] = 257,
  [SMALL_STATE(18)] = 267,
  [SMALL_STATE(19)] = 277,
  [SMALL_STATE(20)] = 287,
  [SMALL_STATE(21)] = 297,
  [SMALL_STATE(22)] = 308,
  [SMALL_STATE(23)] = 319,
  [SMALL_STATE(24)] = 330,
  [SMALL_STATE(25)] = 340,
  [SMALL_STATE(26)] = 350,
  [SMALL_STATE(27)] = 360,
  [SMALL_STATE(28)] = 370,
  [SMALL_STATE(29)] = 377,
  [SMALL_STATE(30)] = 384,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_workspace_block_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_workspace_block_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_workspace_block_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_workspace_block_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_workspace_block_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_model, 2, 0, 1),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_views, 2, 0, 1),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_model_block, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_views_block, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description_statement, 2, 0, 4),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name_statement, 2, 0, 4),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_workspace, 2, 0, 1),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_workspace, 4, 0, 3),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_workspace_block, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_workspace, 3, 0, 2),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_workspace_block, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_workspace, 4, 0, 5),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [92] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_structurizr(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "structurizr",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
